version: "3.8"

services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    depends_on:
      vault:
        condition: service_healthy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  vault: # dev setup for easy testing
    image: vault:1.12.3
    container_name: my_vault
    command: sh -c "vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200 & sleep 2 && vault kv put secret/django POSTGRES_DB=django_db POSTGRES_USER=django_user POSTGRES_PASSWORD=django_password SECRET_KEY=dev_secret_key && vault kv put secret/oauth OAUTH2_CLIENT_ID=test OAUTH2_CLIENT_SECRET=test && wait"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: transcendence_node_app
    volumes:
      - ./app:/app  # Mount for development
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "3000:3000"
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - NODE_ENV=development
    command: npm run dev  # Use development mode with hot reload

volumes:
  db_data: