{
 "title": "Fastify Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Requests by interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(route, method, status_code) (increase(http_request_summary_seconds_count[$__rate_interval]))",
     "legendFormat": "{{method}}({{status_code}}): {{route}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"app:3000\"}[$__rate_interval])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fastify_app\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"fastify_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nodejs_eventloop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p90_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_max_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_mean_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_min_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_stddev_seconds{job=\"fastify_app\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"fastify_app\"}",
     "legendFormat": "fds"
    }
   ]
  }
 ]
}