services:
  app:
    build:
      # context: ../app
      dockerfile: DockerfileProd
    container_name: transcendence_node_app
    volumes:
      - db-data:/app/database # Mount for development
    ports:
      - "3000:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - SERVICE_FQDN_APP_3000

volumes:
  db-data:
