services:
  app:
#    build:
#      context: .
#      dockerfile: DockerfileApp
#    image: ft_transcendence_devcontainer_app:latest

    image: python:3.13.1-bookworm

#    volumes:
#      - ../..:/workspaces:cached

    command: "sleep infinity"
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: