global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'fastify_app'
    static_configs:
      - targets: [ 'app:3000' ]
    metrics_path: '/metrics'

rule_files:
  - alert_rules.yml                 # <- new

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alertmanager:9093" ]
